-- 0011 biblioteca_de_exercicios
--
-- A biblioteca que o Allisson mandou em 27/08/2026, pelo WhatsApp. Sao 121
-- exercicios, e e o que destrava o editor de ficha: sem catalogo nao ha o que
-- colocar dentro de um bloco de treino.
--
-- O que foi ajustado do que ele escreveu, e por que:
--   - fora "demada": palavra incompleta, nao da para saber qual remada e;
--   - fora "remada curvada sulinads": typo de "supinada", e a supinada ja
--     estava na lista;
--   - "Rosca direta banco 45" saiu de ombro para biceps, que e onde ela e;
--   - "hit" virou HIIT, "remada curvada pronado" virou pronada, e
--     "Trices frances" ganhou acento.
-- "Peck deck reverso" e "Crucifixo inverso" ficaram como dois exercicios
-- diferentes, confirmado com o Allisson.
--
-- `equipamento` foi preenchido so onde o proprio nome diz (halter, barra,
-- polia, maquina, Smith). Onde o nome nao revela, fica nulo e o Allisson
-- completa pela tela da biblioteca.
--
-- `video_url` fica nulo de proposito: a decisao e anexar depois, como link do
-- YouTube nao listado, quando ele terminar de gravar e subir tudo. A tela da
-- biblioteca marca quais ainda estao sem video.
--
-- `on conflict do nothing` no indice unico de nome deixa reaplicar sem estrago.

insert into public.exercicio (nome, grupo, equipamento) values
  ('Cross over polia alta', 'peito', 'Polia'),
  ('Cross over polia baixa', 'peito', 'Polia'),
  ('Cross over polia média', 'peito', 'Polia'),
  ('Crucifixo declinado máquina', 'peito', 'Máquina'),
  ('Crucifixo inclinado halter', 'peito', 'Halter'),
  ('Crucifixo inclinado máquina', 'peito', 'Máquina'),
  ('Crucifixo inclinado polia', 'peito', 'Polia'),
  ('Crucifixo reto com halter', 'peito', 'Halter'),
  ('Crucifixo reto máquina', 'peito', 'Máquina'),
  ('Peck deck voador', 'peito', 'Máquina'),
  ('Supino articulado declinado', 'peito', 'Máquina'),
  ('Supino articulado inclinado', 'peito', 'Máquina'),
  ('Supino declinado barra', 'peito', 'Barra'),
  ('Supino inclinado barra', 'peito', 'Barra'),
  ('Supino inclinado halter', 'peito', 'Halter'),
  ('Supino inclinado Smith', 'peito', 'Smith'),
  ('Supino reto com barra', 'peito', 'Barra'),
  ('Supino reto com halter', 'peito', 'Halter'),
  ('Supino vertical máquina', 'peito', 'Máquina'),
  ('Low row neutro', 'costas', 'Máquina'),
  ('Low row pronada', 'costas', 'Máquina'),
  ('Low row supinada', 'costas', 'Máquina'),
  ('Pulldown máquina', 'costas', 'Máquina'),
  ('Pulldown polia', 'costas', 'Polia'),
  ('Puxador alto unilateral diagonal polia', 'costas', 'Polia'),
  ('Puxador articulado máquina', 'costas', 'Máquina'),
  ('Puxador frente neutro máquina', 'costas', 'Máquina'),
  ('Puxador frente pronado', 'costas', 'Polia'),
  ('Puxador frente supinado', 'costas', 'Polia'),
  ('Puxador frente triângulo', 'costas', 'Polia'),
  ('Remada articulada pronada', 'costas', 'Máquina'),
  ('Remada articulada sentada', 'costas', 'Máquina'),
  ('Remada baixa pronada', 'costas', 'Polia'),
  ('Remada baixa supinada', 'costas', 'Polia'),
  ('Remada baixa triângulo', 'costas', 'Polia'),
  ('Remada baixa unilateral', 'costas', 'Polia'),
  ('Remada cavalinho livre', 'costas', null),
  ('Remada cavalinho máquina', 'costas', 'Máquina'),
  ('Remada curvada máquina', 'costas', 'Máquina'),
  ('Remada curvada pronada', 'costas', null),
  ('Remada curvada supinada', 'costas', null),
  ('Remada unilateral halter', 'costas', 'Halter'),
  ('T Bar Row', 'costas', 'Barra'),
  ('Abdução polia', 'pernas', 'Polia'),
  ('Abdução polia banco 45°', 'pernas', 'Polia'),
  ('Afundo unilateral Smith', 'pernas', 'Smith'),
  ('Agachamento búlgaro com halter', 'pernas', 'Halter'),
  ('Agachamento búlgaro no Smith', 'pernas', 'Smith'),
  ('Agachamento pêndulo', 'pernas', null),
  ('Agachamento v-squat', 'pernas', null),
  ('Belt squat', 'pernas', null),
  ('Cadeira abdutora', 'pernas', 'Máquina'),
  ('Cadeira abdutora articulada', 'pernas', 'Máquina'),
  ('Cadeira adutora', 'pernas', 'Máquina'),
  ('Cadeira extensora', 'pernas', 'Máquina'),
  ('Cadeira extensora unilateral', 'pernas', 'Máquina'),
  ('Cadeira flexora', 'pernas', 'Máquina'),
  ('Coice na polia', 'pernas', 'Polia'),
  ('Elevação pélvica', 'pernas', null),
  ('Extensão quadril polia', 'pernas', 'Polia'),
  ('Flexor unilateral máquina', 'pernas', 'Máquina'),
  ('Good morning v-squat', 'pernas', null),
  ('Hack cadeirinha', 'pernas', 'Máquina'),
  ('Hack machine', 'pernas', 'Máquina'),
  ('Hip-press unilateral', 'pernas', null),
  ('Leg 180°', 'pernas', 'Máquina'),
  ('Leg 180° unilateral', 'pernas', 'Máquina'),
  ('Leg press 45°', 'pernas', 'Máquina'),
  ('Mesa flexora', 'pernas', 'Máquina'),
  ('Panturrilha em pé', 'pernas', null),
  ('Panturrilha no leg 180°', 'pernas', 'Máquina'),
  ('Panturrilha sentado', 'pernas', null),
  ('RDL', 'pernas', null),
  ('RDL com halter', 'pernas', 'Halter'),
  ('RDL unilateral', 'pernas', null),
  ('Stif com barra', 'pernas', 'Barra'),
  ('Stif com halter', 'pernas', 'Halter'),
  ('Sumo na máquina', 'pernas', 'Máquina'),
  ('Terra sumo', 'pernas', null),
  ('Crucifixo inverso', 'ombro', null),
  ('Elevação frontal polia', 'ombro', 'Polia'),
  ('Elevação lateral halter', 'ombro', 'Halter'),
  ('Elevação lateral máquina', 'ombro', 'Máquina'),
  ('Elevação unilateral banco 45°', 'ombro', null),
  ('Elevação unilateral polia', 'ombro', 'Polia'),
  ('Encolhimento barra', 'ombro', 'Barra'),
  ('Encolhimento halter', 'ombro', 'Halter'),
  ('Facepull', 'ombro', 'Polia'),
  ('Peck deck reverso', 'ombro', 'Máquina'),
  ('Remada alta', 'ombro', null),
  ('Rosca direta banco 45°', 'biceps', null),
  ('Rosca direta barra W', 'biceps', 'Barra'),
  ('Rosca direta no Cross', 'biceps', 'Polia'),
  ('Rosca martelo halter', 'biceps', 'Halter'),
  ('Rosca Scott', 'biceps', null),
  ('Rosca Scott máquina', 'biceps', 'Máquina'),
  ('Rosca spider', 'biceps', null),
  ('Mergulho máquina', 'triceps', 'Máquina'),
  ('Paralelas', 'triceps', null),
  ('Pulley barra V', 'triceps', 'Polia'),
  ('Pulley corda', 'triceps', 'Polia'),
  ('Tríceps coice polia', 'triceps', 'Polia'),
  ('Tríceps francês', 'triceps', null),
  ('Tríceps francês máquina', 'triceps', 'Máquina'),
  ('Tríceps francês polia', 'triceps', 'Polia'),
  ('Tríceps francês unilateral', 'triceps', null),
  ('Tríceps testa barra W', 'triceps', 'Barra'),
  ('Tríceps testa halter', 'triceps', 'Halter'),
  ('Tríceps testa polia', 'triceps', 'Polia'),
  ('Abdominal', 'abdomen', null),
  ('Abdominal infra solo', 'abdomen', null),
  ('Abdominal infra torre', 'abdomen', null),
  ('Abdominal na polia', 'abdomen', 'Polia'),
  ('Abdominal supra máquina', 'abdomen', 'Máquina'),
  ('Abdominal supra solo', 'abdomen', null),
  ('Prancha abdominal', 'abdomen', null),
  ('Bicicleta', 'cardio', null),
  ('Bicicleta ergométrica', 'cardio', null),
  ('Escadaria', 'cardio', null),
  ('Esteira', 'cardio', null),
  ('HIIT', 'cardio', null)
on conflict do nothing;
